rule("logger.test.logger_test_gen", function()
    local function prepare_test_data(target)
        os.vcp("logger/test/conf/logger.conf", target:rundir(), {rootdir = "logger/test"})
    end

    before_run(prepare_test_data)
    before_test(prepare_test_data)
end)

target("logger.test.logger_test", function()
    set_kind("binary")
    set_default(false)
    -- add_tests("default", {run_timeout = 60 * 1000})
    add_files("logger_test.cc")
    add_deps("logger", "util.macros")
    add_rules("logger.test.logger_test_gen")
end)

target("logger.test.signal8_test", function()
    set_kind("binary")
    set_default(false)
    -- add_tests("default", {run_timeout = 60 * 1000})
    add_files("signal8_test.cc")
    set_rundir("$(projectdir)")
    add_deps("logger")
end)

target("logger.test.funny_test", function()
    set_kind("binary")
    set_default(false)
    -- add_tests("default", {run_timeout = 60 * 1000})
    add_files("funny_test.cc")
    set_rundir("$(projectdir)")
    add_deps("logger")
end)
