target("util.macros", function()
    set_kind("object")
    add_rules("c++")
end)

target("util.macros.macros_test", function()
    set_kind("binary")
    set_default(false)
    add_tests("default", {run_timeout = 60 * 1000})
    add_files("macros_test.cc")
    set_rundir("$(projectdir)")
    add_deps("util.macros")
    add_packages("gtest")
end)
