target("net", function()
    set_kind("object")
    -- add_files("**.cc|**_test.cc")
    add_files("timer.cc")
    add_deps("logger")
end)

target("net.timer_test", function()
    set_kind("binary")
    set_default(false)
    add_files("timer_test.cc")
    add_deps("net")
    add_tests("default")
    add_packages("gtest")
end)
